info:
  profile: default
spring:
  jpa:
    database: HSQL #http://config:8888/zuul/spring
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: true #覆盖非系统属性　true不覆盖
      overrideSystemProperties: false #覆盖系统属性 false不覆盖
