server:
  port: 1111 #应用端口号
spring:
    jpa:
        database: HSQL #http://config:8888/zuul/spring
    cloud:
        config:
            allowOverride: true
            failFast: true
            overrideNone: false #覆盖非系统属性　false覆盖
            overrideSystemProperties: true #覆盖系统属性 true覆盖
test:
    my name is czlxming # http://config:8888/zuul/test

  